require 'net/http'
require 'json'
require 'ostruct'
require_relative '../lib/networking'
require_relative '../lib/formatter'
require_relative '../lib/ui'
require_relative '../lib/crypto-tracker'
require_relative '../lib/coin'